# Generated by Django 4.2.4 on 2024-01-27 15:12

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe_model = apps.get_model("main_app", 'Shoe')
    unique_model = apps.get_model("main_app", "UniqueBrands")

    unique_shoe_brands = shoe_model.objects.values_list("brand", flat= True).distinct()
    for brand in unique_shoe_brands:
        unique_model.objects.create(brand_name= brand)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands)
    ]
