# Generated by Django 4.2.4 on 2024-01-27 15:56

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    persons = person_model.objects.all()
    for person in persons:
        if person.age <= 12:
            person.age_group = "Child"
        elif 13 <= person.age <= 17:
            person.age_group = "Teen"
        elif person.age >= 18:
            person.age_group = "Adult"
        person.save()


def reverse_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    age_group_default = person_model._meta.get_field("age_group").default

    for person in person_model.objects.all():
        person.age_group = age_group_default
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=reverse_age_group)
    ]
