# Generated by Django 4.2.4 on 2024-01-27 16:21

from django.db import migrations


def set_new_price(apps,schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    all_smartphones = smartphone_model.objects.all()
    for smartphone in all_smartphones:
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()


def set_category(apps,schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price >= 750:
            smartphone.category = "Expensive"
        else:
            smartphone.category = "Cheap"
        smartphone.save()


def set_price_and_category(apps,schema_editor):
    set_new_price(apps,schema_editor)
    set_category(apps,schema_editor)


def reverse_price_and_category(apps,schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = 0
        smartphone.category = "empty"
        smartphone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category,reverse_price_and_category)
    ]
