# Generated by Django 4.2.4 on 2024-01-28 09:08
from datetime import timedelta

from django.db import migrations

def modify_delive_and_waranty(apps, schema_editor):
    order_model = apps.get_model("main_app", "Order")
    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == "Pending":
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()

        elif order.status == "Cancelled":
            order.delete()

def reverse_status(apps, schema_editor):
    order_model = apps.get_model("main_app","Order")
    all_orders = order_model.objects.all()

    for order in all_orders:
        order.delivery = ""
        order.warranty = ""
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
        migrations.RunPython(modify_delive_and_waranty, reverse_status)
    ]
